language: node_js
os:
- linux
# somehow building for osx does not work correctly either... - osx
# there is currently an issue with window not finding our tests.- windows
node_js:
- "10.15.0"
before_install:
- npm install -g typescript@3.2.2
- cd src/docs && npm i && cd ../..
dist: trusty
git:
  depth: false
branches:
  only:
  - develop
  - "/^feature\\/.*$/"
matrix:
jobs:
  include:
    - script: "npm run lint"
    - script: "npm run typecheck"
    - script: "npm test"
notifications:
  email:
    on_failure: always
    on_success: change
